# image: https://hub.docker.com/r/bitnami/joomla

version: '3.8'

services:
  joomla:
    image: $APP_REPO:$APP_VERSION
    container_name: $APP_NAME
    restart: always
    ports:
      - ${APP_PORT}:8080
    volumes:
      - joomla:/bitnami/joomla
    environment:
      - JOOMLA_USERNAME=$APP_USER
      - JOOMLA_PASSWORD=$APP_PASSWORD
      - JOOMLA_EMAIL=$APP_EMAIL
      - JOOMLA_SITE_NAME=$APP_SITENAME
      - JOOMLA_LOAD_SAMPLE_DATA=yes
      - JOOMLA_SKIP_BOOTSTRAP=no
      - JOOMLA_DATABASE_TYPE=mysqli
      - JOOMLA_DATABASE_HOST=db
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_NAME=$DB_MYSQL_NAME
      - JOOMLA_DATABASE_USER=$DB_MYSQL_USER
      - JOOMLA_DATABASE_PASSWORD=$DB_MYSQL_PASSWORD
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - db
  db:
    image: mysql:$DB_MYSQL_VERSION
    container_name: $APP_NAME-db
    restart: always
    ports:
     - ${DB_MYSQL_PORT}:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=$DB_MYSQL_NAME
      - MYSQL_USER=$DB_MYSQL_USER
      - MYSQL_PASSWORD=$DB_MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_MYSQL_PASSWORD

networks:
  default:
      name: $APP_NAME

volumes:
  joomla:
  mysql:
